/**
 * Tray icon as base64 PNG - generated by `node scripts/make-tray-icon.mjs`, do not edit by hand.
 *
 * Two sizes are embedded: 16px for 100% display scaling and 32px for 200%. Electron picks between
 * them through image representations, so the tray icon stays sharp on either.
 */
export const TRAY_ICON_16 = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAg0lEQVR42mNgwAN8Dj2QAWEGcoDPoQd9Poce/IfiPlI0FvocevAYSTMMg8QK8Wm09Dn04Biapj40l/yHqrHEphldkQxaWKAbbolsQCg2iROr8mRAGIdFoVgNQNLcd2JV3n8o7kNSS7QB/5HxgBhAnhfIDUTKopHihESVpEy1zERqdgYAfCdnQLRNdyAAAAAASUVORK5CYII=";
export const TRAY_ICON_32 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA5UlEQVR42u1X0QnEIAztIC7iDv66hpBFOkjG8EMcQ3CQHoKFIler1WtyxwkPBIPvmURNluWbh7IBEiiItbIhKhu2jDTXTxBLZYM7EJdIa/ITxELZsFaISyRbMTPO203AqLvjBYG7CMmeH7LX3S2bQuGlFrFihrvfxrcjT6AmAIdO0OZB7BUQ71ytSg51CXBnth6N8GjWDFHZ040IwBNy8GiiR7NlpDmM7NlknE/tDsQlXOmN2QJ0hXyH/gv4aQG0SUhxDckfIvKn+PHPiPY7Ji9IWJRkbIpSNmU5i8aETWvGpjmdOV5DUgggOzl0nwAAAABJRU5ErkJggg==";
